-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SEQUENCE daily_rates_id AS integer;

CREATE TABLE IF NOT EXISTS public.companies
(
    mse_code character varying(10) NOT NULL,
    name character varying(150),
    PRIMARY KEY (mse_code)
);

CREATE TABLE IF NOT EXISTS public.daily_company_rates
(
    id bigint NOT NULL DEFAULT nextval('daily_rates_id'::regclass),
    no character varying ,
    high character varying ,
    low character varying ,
    code character varying(10)  NOT NULL,
    buy numeric,
    sell numeric,
    pcp numeric,
    tcp numeric,
    vol integer,
    div_net numeric,
    div_yield numeric,
    earn_yield numeric,
    pe_ratio numeric,
    pbv_ratio numeric,
    cap money,
    profit money,
    shares bigint,
    date date NOT NULL,
    CONSTRAINT daily_company_rates_pkey PRIMARY KEY (id)
)
END;